/**
 * hoardReport.ts — HOARD-compatible matrix report generation.
 *
 * Generates a structured Markdown report summarising the Harris Matrix,
 * designed for intake by HOARD Phase 5 (Assembly & Export) or Trowel's
 * report drafting pipeline.
 *
 * exports: generateMatrixReport, generateMatrixJson
 * used_by: App.tsx → Export menu
 */

import type { Context, Observation, Phase, Event } from './hmdp';
import { ContextType, RelationshipType } from './hmdp';
import { extractEEDPPaths } from './hoardExport';

export interface MatrixReport {
  markdown: string;
  json: string;
  stats: {
    totalContexts: number;
    positive: number;
    negative: number;
    unknown: number;
    totalRelationships: number;
    directionalEdges: number;
    equalsEdges: number;
    contemporaryEdges: number;
    phases: number;
    events: number;
    eedpPaths: number;
  };
}

export function generateMatrixReport(
  projectName: string,
  contexts: Context[],
  observations: Observation[],
  phases: Phase[],
  events: Event[] = [],
): MatrixReport {
  const stats = computeStats(contexts, observations, phases, events);
  const eedpPaths = extractEEDPPaths(contexts, observations, events);
  const phaseMap = new Map(phases.map(p => [p.id, p]));

  let md = '';

  // ── Header ────────────────────────────────────────────────────────────────
  md += `# Harris Matrix Report: ${projectName || 'Untitled Project'}\n\n`;
  md += `> Generated by StratiGraph — Harris Matrix Generator\n`;
  md += `> ${new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}\n\n`;
  md += `---\n\n`;

  // ── Summary ───────────────────────────────────────────────────────────────
  md += `## 1. Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Total stratigraphic units | ${stats.totalContexts} |\n`;
  md += `| Positive (deposits) | ${stats.positive} |\n`;
  md += `| Negative (cuts) | ${stats.negative} |\n`;
  md += `| Unknown type | ${stats.unknown} |\n`;
  md += `| Relationships | ${stats.totalRelationships} |\n`;
  md += `| Phases | ${stats.phases} |\n`;
  md += `| Radiocarbon events | ${stats.events} |\n`;
  md += `| Linearised paths (EEDP) | ${stats.eedpPaths} |\n\n`;

  // ── Context Catalogue ─────────────────────────────────────────────────────
  md += `## 2. Context Catalogue\n\n`;
  md += `| ID | Type | Phase | Period | Description |\n`;
  md += `|----|------|-------|--------|-------------|\n`;

  for (const ctx of contexts) {
    const phase = ctx.phase ? phaseMap.get(ctx.phase) : undefined;
    const typeLabel = ctx.type === ContextType.Positive ? 'Deposit'
      : ctx.type === ContextType.Negative ? 'Cut'
      : 'Unknown';
    const desc = (ctx.description || '').replace(/\n/g, ' ').slice(0, 80);
    md += `| ${ctx.id} | ${typeLabel} | ${phase?.name || '—'} | ${ctx.period || '—'} | ${desc || '—'} |\n`;
  }
  md += '\n';

  // ── Phase Summary ─────────────────────────────────────────────────────────
  if (phases.length > 0) {
    md += `## 3. Phases\n\n`;
    for (const phase of phases) {
      const assigned = contexts.filter(c => c.phase === phase.id).length;
      md += `- **${phase.name}** — ${assigned} context${assigned !== 1 ? 's' : ''}\n`;
    }
    md += '\n';
  }

  // ── Stratigraphic Narrative ───────────────────────────────────────────────
  md += `## 4. Stratigraphic Sequence\n\n`;
  md += `The following linearised paths represent the stratigraphic sequence from youngest (top) to oldest (bottom).\n\n`;

  if (eedpPaths.length === 0) {
    md += `*No stratigraphic relationships defined.*\n\n`;
  } else {
    for (let i = 0; i < eedpPaths.length; i++) {
      const path = eedpPaths[i];
      md += `### Path ${i + 1}\n\n`;
      md += `| Order | Context | Type | Description |\n`;
      md += `|-------|---------|------|-------------|\n`;

      for (let j = 0; j < path.nodes.length; j++) {
        const node = path.nodes[j];
        const typeLabel = node.type === ContextType.Positive ? 'Deposit'
          : node.type === ContextType.Negative ? 'Cut'
          : 'Unknown';
        const desc = (node.description || '').replace(/\n/g, ' ').slice(0, 60);
        md += `| ${j + 1} | ${node.id} | ${typeLabel} | ${desc || '—'} |\n`;
      }
      md += '\n';
    }
  }

  // ── Relationship Summary ──────────────────────────────────────────────────
  md += `## 5. Relationships\n\n`;
  md += `| Type | Count |\n`;
  md += `|------|-------|\n`;
  md += `| Above / Below | ${stats.directionalEdges} |\n`;
  md += `| Equals | ${stats.equalsEdges} |\n`;
  md += `| Contemporary | ${stats.contemporaryEdges} |\n`;
  md += `| **Total** | **${stats.totalRelationships}** |\n\n`;

  // ── HOARD Compatibility Header ────────────────────────────────────────────
  md += `---\n\n`;
  md += `*Report format: HOARD Phase 5 compatible. `;
  md += `Can be ingested by Trowel or HOARD's Assembly pipeline for DOCX/PDF export.*\n`;

  // ── JSON payload ──────────────────────────────────────────────────────────
  const jsonPayload = {
    report: {
      project: projectName || 'Untitled Project',
      generator: 'StratiGraph',
      schema: 'matrix-report-v1',
      generatedAt: new Date().toISOString(),
    },
    stats,
    contexts: contexts.map(ctx => ({
      id: ctx.id,
      type: ctx.type,
      period: ctx.period || null,
      phase: ctx.phase || null,
      description: ctx.description || null,
    })),
    phases: phases.map(p => ({ id: p.id, name: p.name, color: p.color })),
    relationships: observations,
    eedpPaths: eedpPaths.map(p => ({
      nodes: p.nodes.map(n => n.id),
    })),
  };

  return {
    markdown: md,
    json: JSON.stringify(jsonPayload, null, 2),
    stats,
  };
}

function computeStats(
  contexts: Context[],
  observations: Observation[],
  phases: Phase[],
  events: Event[],
): MatrixReport['stats'] {
  return {
    totalContexts: contexts.length,
    positive: contexts.filter(c => c.type === ContextType.Positive).length,
    negative: contexts.filter(c => c.type === ContextType.Negative).length,
    unknown: contexts.filter(c => c.type === ContextType.Unknown).length,
    totalRelationships: observations.length,
    directionalEdges: observations.filter(
      o => o.relationshipType === RelationshipType.Above || o.relationshipType === RelationshipType.Below,
    ).length,
    equalsEdges: observations.filter(o => o.relationshipType === RelationshipType.Equals).length,
    contemporaryEdges: observations.filter(o => o.relationshipType === RelationshipType.Contemporary).length,
    phases: phases.length,
    events: events.length,
    eedpPaths: 0, // computed later
  };
}
